name: Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write # Required for OIDC trusted publishing
  contents: write # Required for creating releases
  pull-requests: write # Required for changesets to update PRs

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'evoluhq/evolu'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@ff41c74480e92d179c27462a68d60e4e4ccb5e06 # v2.0.1
        with:
          bun-version: "1.3.10"

      - name: Install dependencies
        run: bun install

      - name: Verify
        run: bun run verify

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@aba2c841fbc6b30f889c450c3995817c1bf05285 # v1
        with:
          publish: bun run changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
