name: Web Build

on:
  workflow_dispatch:
  # pull_request:
  #   branches: ["*"]
  #   paths:
  #     - "apps/web/**"
  # push:
  #   branches: ["main"]
  #   paths:
  #     - "apps/web/**"
  # merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24e6c9b0f9a0ac08cf17f7ad # v2.0.1

      - name: Install dependencies
        run: bun install

      - name: Build Web
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: bun run build && bun run build:web
